# Generated by Django 2.2 on 2019-02-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=10)),
                ('Tmax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Tmin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Rainfall', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
