# Generated by Django 2.2 on 2019-02-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='Rainfall',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='Tmax',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='Tmin',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='metrics',
            unique_together={('date', 'place')},
        ),
    ]
